services:
  postgres-test:
    container_name: codeflow-postgres-test
    image: postgres:16
    restart: 'no'
    environment:
      POSTGRES_USER: codeflow_user
      POSTGRES_PASSWORD: codeflow_password
      POSTGRES_DB: codeflow_test_db
    ports:
      - '5433:5432'
    tmpfs:
      # Use tmpfs for faster test database (in-memory)
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=100m
    command: |
      postgres 
      -c shared_buffers=128MB 
      -c max_connections=100
      -c fsync=off 
      -c synchronous_commit=off
      -c full_page_writes=off
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
